import { v4 as uuidv4 } from "uuid";

export const ListaVeiculosInicial = [
  {
    id: uuidv4(),
    marca: "Volkswagen",
    modelo: "Fusca",
    imagem: "",
    vaga: "01",
    placa: "AAA1234",
    favorito: true,
    piso: "Térreo",
  },
  {
    id: uuidv4(),
    marca: "Chevrolet",
    modelo: "S10",
    imagem: "",
    vaga: "01",
    placa: "SAD1234",
    favorito: false,
    piso: "1° Andar",
  },
  {
    id: uuidv4(),
    marca: "Chevrolet",
    modelo: "Onix",
    imagem: "",
    vaga: "02",
    placa: "SVA5134",
    favorito: false,
    piso: "Térreo",
  },
  {
    id: uuidv4(),
    marca: "Range Rover",
    modelo: "Velar",
    imagem: "",
    vaga: "01",
    placa: "SNX3421",
    favorito: true,
    piso: "2° Andar",
  },
  {
    id: uuidv4(),
    marca: "Ford",
    modelo: "Fiesta",
    imagem: "",
    vaga: "03",
    placa: "MSA3485",
    favorito: true,
    piso: "Térreo",
  },
  {
    id: uuidv4(),
    marca: "Renault",
    modelo: "Kwid",
    imagem: "",
    vaga: "04",
    placa: "UIA3536",
    favorito: false,
    piso: "Térreo",
  },
  {
    id: uuidv4(),
    marca: "Hyundai",
    modelo: "Azera",
    imagem: "",
    vaga: "03",
    placa: "JKA5824",
    favorito: true,
    piso: "1° Andar",
  },
  {
    id: uuidv4(),
    marca: "Honda",
    modelo: "Civic",
    imagem: "",
    vaga: "02",
    placa: "KLA4235",
    favorito: false,
    piso: "1° Andar",
  },
  {
    id: uuidv4(),
    marca: "Volkswagen",
    modelo: "Amarok",
    imagem: "",
    vaga: "05",
    placa: "KSN3582",
    favorito: false,
    piso: "1° Andar",
  },
  {
    id: uuidv4(),
    marca: "Volkswagen",
    modelo: "UP",
    imagem: "",
    vaga: "07",
    placa: "OIR4335",
    favorito: false,
    piso: "Térreo",
  },
  {
    id: uuidv4(),
    marca: "Volkswagen",
    modelo: "Gol",
    imagem: "",
    vaga: "03",
    placa: "KNE4359",
    favorito: false,
    piso: "2° Andar",
  },
  {
    id: uuidv4(),
    marca: "Chevrolet",
    modelo: "Camaro",
    imagem: "",
    vaga: "02",
    placa: "MYA5835",
    favorito: false,
    piso: "2° Andar",
  },
  {
    id: uuidv4(),
    marca: "Lamborghini",
    modelo: "Aventador",
    imagem: "",
    vaga: "02",
    placa: "AAN3940",
    favorito: true,
    piso: "3° Andar",
  },
];

export const ListaPisosInicial = [
  {
    id: uuidv4(),
    nome: "Térreo",
    cor: "#57c278",
  },
  {
    id: uuidv4(),
    nome: "1° Andar",
    cor: "#82CFFA",
  },
  {
    id: uuidv4(),
    nome: "2° Andar",
    cor: "#A6D157",
  },
  {
    id: uuidv4(),
    nome: "3° Andar",
    cor: "#E06B69",
  },
  {
    id: uuidv4(),
    nome: "4° Andar",
    cor: "#DB6EBF",
  },
  {
    id: uuidv4(),
    nome: "5° Andar",
    cor: "#FFBA05",
  },
  {
    id: uuidv4(),
    nome: "6° Andar",
    cor: "#FF8A29",
  },
];
